-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isBanned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resetOtp" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resetOtpExpires" TIMESTAMP(3); 